version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine
    container_name: zenith_postgres
    environment:
      POSTGRES_USER: zenithuser
      POSTGRES_PASSWORD: zenithpassword
      POSTGRES_DB: zenith_db
    ports:
      # Exposes the container's port 5432 to your Mac's port 5432
      - "5432:5432"
    volumes:
      # This ensures your database data persists even if you stop the container
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenithuser -d zenith_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Zookeeper Service (Required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zenith_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Apache Kafka Service (Message Broker)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: zenith_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# Defines the named volume for data persistence
volumes:
  postgres_data: